name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -f -y
        sudo apt install -y python3-pip build-essential git python3 python3-dev
        sudo apt install -y libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev
        sudo apt install -y libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev
        sudo apt install -y zlib1g-dev libunwind-dev
        sudo apt install -y libgstreamer1.0-dev gstreamer1.0-plugins-{bad,base,good,ugly}
        sudo apt install -y cmake pkg-config libjpeg-dev libtiff5-dev libpng-dev
        sudo apt install -y libgirepository1.0-dev libssl-dev openjdk-8-jdk
    
    - name: Install Buildozer and dependencies
      run: |
        pip install buildozer cython
    
    - name: Setup Android licenses
      run: |
        mkdir -p $ANDROID_HOME/licenses
        echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > $ANDROID_HOME/licenses/android-sdk-license
        echo "84831b9409646a918e30573bab4c9c91346d8abd" > $ANDROID_HOME/licenses/android-sdk-preview-license
        echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > $ANDROID_HOME/licenses/android-sdk-license
        echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > $ANDROID_HOME/licenses/android-sdk-license
    
    - name: Build APK
      env:
        ANDROID_HOME: /home/runner/.buildozer/android/platform/android-sdk
        ANDROID_SDK_ROOT: /home/runner/.buildozer/android/platform/android-sdk
        ANDROID_SDK_LICENSE: "24333f8a63b6825ea9c5514f83c2829b004d1fee"
        ANDROID_SDK_PREVIEW_LICENSE: "84831b9409646a918e30573bab4c9c91346d8abd"
      run: |
        buildozer android debug
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: filemessenger-apk
        path: bin/*.apk 
