name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip build-essential git python3 python3-dev
        sudo apt install -y libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev
        sudo apt install -y libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev
        sudo apt install -y zlib1g-dev libgstreamer1.0-dev gstreamer1.0-plugins-{bad,base,good,ugly}
        sudo apt install -y cmake pkg-config libjpeg-dev libtiff5-dev libjasper-dev libpng-dev
        sudo apt install -y libgirepository1.0-dev libssl-dev openjdk-8-jdk
    
    - name: Install Buildozer
      run: |
        pip install buildozer
    
    - name: Build APK
      run: |
        buildozer android debug
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: filemessenger-apk
        path: bin/*.apk 
